export type Row = Record<string, string | number>;
export interface Field { key: string; label: string; type?: string; options?: string[]; optional?: boolean; }
export interface Section { title: string; singular: string; description: string; fields: Field[]; rows: Row[]; filter: string; }
const field = (key: string, label: string, type = 'text', options?: string[]): Field => ({key,label,type,options});
const eventFields = [field('clientId','Client','client'),field('eventType','Event type','select',['WEDDING','CORPORATE_EVENT','CONFERENCE','OFFICIAL_RECEPTION','ANNIVERSARY','BIRTHDAY','GALA_DINNER','PRODUCT_LAUNCH','PRIVATE_PARTY','OTHER']),field('date','Event date','date'),field('totalCost','Total cost (₾)','number'),field('guestCount','Guests','number'),field('location','Location','select',['AURUM_BANQUET_HALL','AURUM_CONFERENCE_HALL','PRIVATE_RESIDENCE','PARTNER_VENUE','HOTEL','RESTAURANT','OUTDOOR_VENUE','HISTORICAL_VENUE','CORPORATE_OFFICE','OTHER']),field('status','Status','select',['REQUESTED','PLANNING','CONFIRMED','COMPLETED','REJECTED','CANCELLED']),{...field('notes','Notes','textarea'),optional:true}];
export const sections: Record<string,Section> = {
 events: {title:'Events',singular:'event',description:'Every detail, from the first idea to the final toast.',filter:'status',fields:eventFields,rows:[
 {id:1001,clientId:1,eventType:'WEDDING',date:'2026-10-18',totalCost:24500,guestCount:160,location:'AURUM_BANQUET_HALL',status:'CONFIRMED',notes:'Ivory florals and a live quartet.'},
 {id:1002,clientId:2,eventType:'PRODUCT_LAUNCH',date:'2026-10-24',totalCost:18200,guestCount:90,location:'AURUM_CONFERENCE_HALL',status:'PLANNING',notes:'Stage and presentation equipment required.'},
 {id:1003,clientId:3,eventType:'BIRTHDAY',date:'2026-11-02',totalCost:6400,guestCount:35,location:'PRIVATE_RESIDENCE',status:'REQUESTED',notes:'An intimate evening with a seasonal menu.'},
 {id:1004,clientId:2,eventType:'GALA_DINNER',date:'2026-11-12',totalCost:31000,guestCount:200,location:'HOTEL',status:'REQUESTED',notes:'Welcome drinks at 19:00.'},
 {id:1005,clientId:1,eventType:'ANNIVERSARY',date:'2026-08-20',totalCost:8200,guestCount:45,location:'RESTAURANT',status:'COMPLETED',notes:'Completed with excellent feedback.'}]},
 clients:{title:'Clients',singular:'client',description:'Personal connections. Exceptional experiences.',filter:'type',fields:[field('name','Name'),field('email','Email','email'),field('phone','Phone','tel'),field('type','Client type','select',['PERSON','ORGANIZATION'])],rows:[{id:1,name:'Nino & Giorgi',email:'nino@example.com',phone:'+995 555 010 101',type:'PERSON'},{id:2,name:'Atelier Group',email:'events@example.com',phone:'+995 555 010 202',type:'ORGANIZATION'},{id:3,name:'Mariam Dadiani',email:'mariam@example.com',phone:'+995 555 010 303',type:'PERSON'}]},
 employees:{title:'Employees',singular:'employee',description:'The people behind every remarkable occasion.',filter:'type',fields:[field('name','Full name'),field('type','Specialty','select',['SALES_MANAGER','CLIENT_MANAGER','PURCHASING_MANAGER','MUSICIAN','ACTOR','DRIVER','HOST','CHEF']),field('salary','Salary (₾)','number'),field('email','Email','email'),field('role','Access role','select',['OWNER','ADMIN','STAFF','DEMO'])],rows:[{id:1,name:'Ana Beridze',type:'CLIENT_MANAGER',salary:3200,email:'ana@example.com',role:'ADMIN'},{id:2,name:'Luka Kapanadze',type:'CHEF',salary:4500,email:'luka@example.com',role:'STAFF'},{id:3,name:'Salome Japaridze',type:'HOST',salary:2400,email:'salome@example.com',role:'STAFF'},{id:4,name:'Davit Maisuradze',type:'DRIVER',salary:2200,email:'davit@example.com',role:'STAFF'}]},
 vehicles:{title:'Vehicles',singular:'vehicle',description:'A considered fleet for guests and everything they need.',filter:'type',fields:[field('type','Vehicle type','select',['TRUCK','PASSENGER_VEHICLE']),field('passengerCapacity','Passenger capacity','number'),field('cargoWeightLimit','Cargo limit (kg)','number')],rows:[{id:1,type:'PASSENGER_VEHICLE',passengerCapacity:16,cargoWeightLimit:250},{id:2,type:'TRUCK',passengerCapacity:2,cargoWeightLimit:3500},{id:3,type:'PASSENGER_VEHICLE',passengerCapacity:7,cargoWeightLimit:150}]},
 products:{title:'Products',singular:'product',description:'The essentials that bring every occasion together.',filter:'category',fields:[field('productName','Product name'),field('category','Category'),field('price','Unit price (₾)','number'),field('supplierId','Supplier','supplier'),field('quantity','Quantity','number')],rows:[{id:1,productName:'Linen napkins · ivory',category:'Tableware',price:12,supplierId:1,quantity:280},{id:2,productName:'Crystal wine glasses',category:'Glassware',price:24,supplierId:1,quantity:180},{id:3,productName:'Seasonal white flowers',category:'Florals',price:65,supplierId:2,quantity:45},{id:4,productName:'Pillar candles',category:'Decor',price:18,supplierId:3,quantity:120}]},
 suppliers:{title:'Suppliers',singular:'supplier',description:'Trusted partners, thoughtfully selected.',filter:'city',fields:[field('partnerNumber','Partner number'),field('productType','Product type'),field('city','City'),field('street','Street'),field('number','Building number')],rows:[{id:1,partnerNumber:'SUP-001',productType:'Tableware & glassware',city:'Tbilisi',street:'Aghmashenebeli Avenue',number:'24'},{id:2,partnerNumber:'SUP-002',productType:'Fresh flowers',city:'Tbilisi',street:'Abashidze Street',number:'18'},{id:3,partnerNumber:'SUP-003',productType:'Event decor',city:'Kutaisi',street:'Rustaveli Avenue',number:'12'}]},
 menu:{title:'Menu',singular:'menu item',description:'A collection of dishes for memorable gatherings.',filter:'category',fields:[field('name','Dish name'),field('category','Category','select',['APPETIZER','MAIN_COURSE','DESSERT','DRINK']),field('pricePerPerson','Price per person (₾)','number')],rows:[{id:1,name:'Seasonal pkhali selection',category:'APPETIZER',pricePerPerson:18},{id:2,name:'Herb-roasted chicken',category:'MAIN_COURSE',pricePerPerson:42},{id:3,name:'Berry mille-feuille',category:'DESSERT',pricePerPerson:22},{id:4,name:'Tarragon & citrus lemonade',category:'DRINK',pricePerPerson:12}]},
 feedback:{title:'Feedback',singular:'feedback',description:'Listen closely. Make the next experience even better.',filter:'rating',fields:[field('eventId','Event','event'),field('author','Author'),field('commentDate','Comment date','date'),field('rating','Rating','select',['1','2','3','4','5']),field('description','Description','textarea')],rows:[{id:1,eventId:1005,author:'Nino',commentDate:'2026-08-21',rating:5,description:'Beautifully organised. Every detail felt personal, from the table setting to the service.'},{id:2,eventId:1005,author:'Giorgi',commentDate:'2026-08-22',rating:4,description:'A wonderful evening and a fantastic menu. Thank you to the whole team.'}]}
};
