import { Row } from '../shared/staff-row';

export const eventsSeed: Row[] = [
  {
    id: 1001,
    clientId: 1,
    eventType: 'WEDDING',
    date: '2026-10-18',
    totalCost: 24500,
    guestCount: 160,
    location: 'AURUM_BANQUET_HALL',
    status: 'CONFIRMED',
    notes: 'Ivory florals and a live quartet.',
  },
  {
    id: 1002,
    clientId: 2,
    eventType: 'PRODUCT_LAUNCH',
    date: '2026-10-24',
    totalCost: 18200,
    guestCount: 90,
    location: 'AURUM_CONFERENCE_HALL',
    status: 'PLANNING',
    notes: 'Stage and presentation equipment required.',
  },
  {
    id: 1003,
    clientId: 3,
    eventType: 'BIRTHDAY',
    date: '2026-11-02',
    totalCost: 6400,
    guestCount: 35,
    location: 'PRIVATE_RESIDENCE',
    status: 'REQUESTED',
    notes: 'An intimate evening with a seasonal menu.',
  },
  {
    id: 1004,
    clientId: 2,
    eventType: 'GALA_DINNER',
    date: '2026-11-12',
    totalCost: 31000,
    guestCount: 200,
    location: 'HOTEL',
    status: 'REQUESTED',
    notes: 'Welcome drinks at 19:00.',
  },
  {
    id: 1005,
    clientId: 1,
    eventType: 'ANNIVERSARY',
    date: '2026-08-20',
    totalCost: 8200,
    guestCount: 45,
    location: 'RESTAURANT',
    status: 'COMPLETED',
    notes: 'Completed with excellent feedback.',
  },
];
